---
title: "Assignment 10: How much for that car?"
author: "FirstName LastName"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    dev: pdf
    highlight: tango
  html_document:
    theme: default
    self_contained: true
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    smart: true
    dev: svg
---

```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
is_pdf <- try (("pdf_document" %in% rmarkdown::all_output_formats(knitr::current_input())), silent=TRUE)
is_pdf <- (is_pdf == TRUE)
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(broom))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(plotly))
# Load dataset
car_prices <- read_rds("car_price_data.rds")
```


## Exercise 1
```{r, echo=FALSE}
car_prices %>%
  pivot_longer(cols = c(Liter, Mileage), 
               names_to = "Variable", 
               values_to = "Value") %>%
  ggplot(aes(x = Value, y = Price)) +
  geom_point() +
  facet_wrap(~Variable, scales = "free_x") +
  labs(title = "Price vs. Liter and Mileage",
       x = "Value",
       y = "Price")
```


## Exercise 2
```{r, echo=FALSE}
continuous_model <- lm(Price ~ Liter + Mileage, data = car_prices)

tidy(continuous_model)

glance(continuous_model)$r.squared
```


## Exercise 3
```{r}
lit <- unique(car_prices$Liter)
mil <- unique(car_prices$Mileage)
grid <- with(car_prices, expand.grid(lit, mil))
d <- setNames(data.frame(grid), c("Liter", "Mileage"))
vals <- predict(continuous_model, newdata = d)

m <- matrix(vals, nrow = length(unique(d$Liter)), ncol = length(unique(d$Mileage)))

p <- plot_ly() %>%
  add_markers(
    x = ~car_prices$Mileage,
    y = ~car_prices$Liter,
    z = ~car_prices$Price,
    marker = list(size = 1)
  ) %>%
  add_trace(
    x = ~mil,
    y = ~lit,
    z = ~m,
    type = "surface",
    colorscale = list(c(0,1), c("yellow", "yellow")),
    showscale = FALSE
  ) %>%
  layout(
    scene = list(
      xaxis = list(title = "Mileage"),
      yaxis = list(title = "Liters"),
      zaxis = list(title = "Price")
    )
  )

if (!is_pdf) { p }
```


## Exercise 4
```{r, echo=FALSE}
continuous_df <- car_prices %>%
  add_predictions(continuous_model) %>%
  add_residuals(continuous_model)

head(continuous_df)
```



## Exercise 5
```{r, echo=FALSE}
continuous_df %>%
  ggplot() +
  geom_point(mapping = aes(x = pred, y = Price)) +
  geom_abline(slope = 1, intercept = 0, color = "red") +
  labs(
    title = "Observed vs Predicted Prices",
    x = "Predicted Price",
    y = "Observed Price"
  )
```


## Exercise 6
```{r, echo=FALSE}
continuous_df %>%
  ggplot() +
  geom_point(mapping = aes(x = pred, y = resid)) +
  geom_hline(yintercept = 0, color = "red") +
  labs(
    title = "Residuals vs Predicted Prices",
    x = "Predicted Price",
    y = "Residuals"
  )
```



## Exercise 7
```{r, echo=FALSE}
continuous_df %>%
  ggplot() +
  geom_qq(aes(sample = resid)) +
  geom_qq_line(aes(sample = resid)) +
  labs(title = "Q-Q Plot of Residuals")
```



## Exercise 8
```{r, echo=FALSE}
car_prices %>%
  ggplot() +
  geom_boxplot(aes(x = reorder(Make, Price, FUN = median), y = Price)) +
  labs(
    x = "Make of car",
    y = "Price",
    title = "Effect of make of car on price"
  )
```



## Exercise 9




## Exercise 10




## Exercise 11




## Exercise 12




## Academic Integrity statement
