---
title: "Assignment 11: Surviving the Titanic"
author: "MinJae Jo"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    dev: pdf
    highlight: tango
  html_document:
    theme: default
    self_contained: true
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    smart: true
    dev: svg
---

```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
# Cost function for cross validation
cost <- function(obs, pred) {
  outcome <- pred > 0.5
  return(1 - (sum(obs == outcome) / length(obs)))
}
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(modelr))
suppressPackageStartupMessages(library(boot))
```


## Exercise 1
```{r}
library(readr)
library(dplyr)

train_df <- read_csv(
  file = "train.csv",
  col_types = cols(
    Pclass = col_character(),
    SibSp = col_character(),
    Parch = col_character()
  )
)

train_df <- train_df %>%
  mutate(did_survive = as.logical(Survived))
```

## Exercise 2
```{r, echo=FALSE}
library(tidyr)
library(ggplot2)

train_df %>%
  pivot_longer(cols = c(Age, Fare), names_to = "variable", values_to = "value") %>%
  ggplot() +
  geom_histogram(aes(x = value, fill = did_survive), bins = 30, alpha = 0.7, position = "identity") +
  facet_wrap(~ variable, scales = "free") +
  labs(
    x = "Value",
    y = "Count",
    title = "Distributions of Age and Fare by Survival Status",
    fill = "Survived"
  )
```

## Exercise 3
```{r, echo=FALSE}
train_df %>%
  pivot_longer(cols = c(Pclass, Sex, Parch, SibSp),
               names_to = "variable",
               values_to = "value") %>%
  ggplot() +
  geom_bar(aes(x = value, fill = did_survive)) +
  facet_wrap(~ variable, scales = "free") +
  labs(
    x = "Category",
    y = "Count",
    title = "Categorical Variables and Survival on the Titanic",
    fill = "Survived"
  )
```

## Exercise 4
```{r, echo=FALSE}
ggplot(train_df, aes(x = Pclass, fill = did_survive)) +
  geom_bar() +
  facet_wrap(~ Sex) +
  labs(
    x = "Passenger Class",
    y = "Count",
    title = "Survival by Passenger Class and Sex",
    fill = "Survived"
  )
```


## Exercise 5
```{r, echo=FALSE}
train_df %>%
  summarize(
    count = n(),
    missing = sum(is.na(Age)),
    fraction_missing = mean(is.na(Age))
  )
train_imputed <- train_df %>%
  mutate(
    age_imputed = if_else(
      condition = is.na(Age),
      true = median(Age, na.rm = TRUE),
      false = Age
    )
  )
train_imputed %>%
  summarize(
    missing_age_imputed = sum(is.na(age_imputed))
  )
```


## Exercise 6
```{r, echo=FALSE}
library(modelr)

model_1 <- glm(Survived ~ age_imputed, data = train_imputed, family = "binomial")

model_1_preds <- train_imputed %>%
  add_predictions(model_1, type = "response") %>%
  mutate(outcome = if_else(pred > 0.5, 1, 0))

model_1_preds %>%
  mutate(
    correct = if_else(Survived == outcome, 1, 0)
  ) %>%
  summarize(
    total_correct = sum(correct),
    accuracy = mean(correct)
  )
```


## Exercise 7
```{r, echo=FALSE}
cost <- function(r, pi = 0) {
  mean(abs(r - round(pi)))
}

library(boot)
logistic_cv1 <- cv.glm(train_imputed, model_1, cost, K = 5)

logistic_cv1$delta
```


## Exercise 8
```{r, echo=FALSE}
model_2 <- glm(Survived ~ age_imputed + SibSp + Pclass + Sex,
               data = train_imputed, family = "binomial")

logistic_cv2 <- cv.glm(train_imputed, model_2, cost, K = 5)
logistic_cv2$delta


model_3 <- glm(Survived ~ age_imputed * Pclass * Sex + SibSp,
               data = train_imputed, family = "binomial")

logistic_cv3 <- cv.glm(train_imputed, model_3, cost, K = 5)
logistic_cv3$delta
```


## Bonus Exercise

If you choose to do the bonus exercise, write your code here. Otherwise you can delete this section.



## Academic Integrity statement
