---
title: "Assignment 9: Birth Times"
author: "FirstName LastName"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    dev: pdf
    highlight: tango
  html_document:
    theme: default
    self_contained: true
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    smart: true
    dev: svg
---

```{r setup, include = FALSE}
# DO NOT ALTER THIS CHUNK
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  out.width = "70%",
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(infer))
# Load Cohen's d bootstrap helper functions
load("bootstrap_cohens_d.RData")
# Load dataset
nsfg6 <- read_rds("2002FemPreg.rds")
# Set seed
set.seed(361356566)
```
## Exercise 1
```{r ex1}
live_births <- dplyr::filter(nsfg6, outcome == 1)
pregnancy_length <- dplyr::mutate(
  live_births,
  birth_order = dplyr::if_else(birthord == 1, "first", "other")
) |>
  dplyr::select(prglngth, birth_order)
```

## Exercise 2
```{r ex2, echo=FALSE}
library(ggplot2)

# PMF-style overlapping histograms (binwidth = 1), same plot, transparent
ggplot(pregnancy_length, aes(x = prglngth, fill = birth_order)) +
  geom_histogram(
    aes(y = after_stat(count / sum(count))),
    binwidth = 1,
    position = "identity",
    alpha = 0.5,
    boundary = 0,
    closed = "left"
  ) +
  xlim(27, 46) +
  labs(
    title = "Pregnancy length (weeks): first vs. other births",
    x = "Weeks of gestation",
    y = "Probability (PMF)",
    fill = "Birth order"
  )
```


## Exercise 3
```{r, echo=FALSE}
pregnancy_length %>%
  group_by(birth_order) %>%
  summarize(
    mean = mean(prglngth, na.rm = TRUE),
    median = median(prglngth, na.rm = TRUE),
    sd = sd(prglngth, na.rm = TRUE),
    IQR = IQR(prglngth, na.rm = TRUE),
    min = min(prglngth, na.rm = TRUE),
    max = max(prglngth, na.rm = TRUE)
  )
```

## Exercise 4




## Exercise 5




## Exercise 6




## Exercise 7