---
title: "Assignment 5: Modeling COVID-19"
author: "MinJae Jo"
date: "`r Sys.Date()`"
documentclass: article
geometry: margin=1in
fontsize: 11pt
output:
  pdf_document:
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    dev: pdf
    highlight: tango
  html_document:
    theme: default
    self_contained: true
    toc: false
    df_print: kable
    fig_caption: false
    number_sections: false
    smart: true
    dev: svg
---

```{r setup, include = FALSE, echo=FALSE}
# DO NOT ALTER THIS CHUNK
knitr::opts_chunk$set(
  echo = TRUE,
  eval = TRUE,
  fig.width = 5,
  fig.asp = 0.618,
  dpi = 120,
  fig.align = "center",
  cache = FALSE
)
# Load required packages
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(scales))
covid_real <- read_csv("covid_counts.csv")
```


## Exercise 1
```{r}
days_range <- 1:250
```



## Exercise 2
```{r}
susceptible <- 300000000
infectious  <- 1
recovered   <- 0
```



## Exercise 3
```{r}
beta  <- 0.25
gamma <- 0.125
N     <- 300000001

for(day in 2:250){
  susceptible[day] <- susceptible[day - 1] - (beta  * susceptible[day - 1] * infectious[day - 1]) / N
  infectious[day]  <- infectious[day - 1]  + (beta  * susceptible[day - 1] * infectious[day - 1]) / N - (gamma * infectious[day - 1])
  recovered[day]   <- recovered[day - 1]   + (gamma * infectious[day - 1])
}
```


## Exercise 4
```{r}
library(tibble)

covid_sim <- tibble(
  day        = days_range,
  susceptible = susceptible,
  infectious  = infectious,
  recovered   = recovered
)
```


## Exercise 5
```{r}
library(ggplot2)
library(tidyr)

covid_long <- covid_sim %>%
  pivot_longer(cols = c(susceptible, infectious, recovered),
               names_to = "category",
               values_to = "count")

ggplot(covid_long, aes(x = day, y = count, color = category)) +
  geom_line(size = 1) +
  labs(
    title = "Simulated COVID-19 cases from SIR model",
    x = "Days in USA",
    y = "Number of People"
  ) +
  theme_minimal()
```


## Exercise 6
```{r}
library(ggplot2)

ggplot() +
  geom_line(data = covid_sim, aes(x = day, y = infectious, color = "Simulated Infectious")) +
  geom_line(data = covid_real, aes(x = days_in_country, y = current_cases, color = "Actual Current Cases")) +
  labs(
    title = "Simulated vs Actual COVID-19 Cases",
    x = "Days",
    y = "Number of People"
  ) +
  theme_minimal()
```


## Exercise 7
```{r}
library(ggplot2)
library(scales)

ggplot() +
  geom_line(data = covid_sim, aes(x = day, y = infectious, color = "Simulated Infectious")) +
  geom_line(data = covid_real, aes(x = days_in_country, y = current_cases, color = "Actual Current Cases")) +
  labs(
    title = "Simulated vs Actual COVID-19 Cases (log scale)",
    x = "Days",
    y = "Number of People"
  ) +
  theme_minimal() +
  scale_y_log10(labels = trans_format("log10", math_format(10^.x)))
```


## Exercise 8




## Academic Integrity statement
